from flask import Flask, render_template
import json
import os
import subprocess

app = Flask(__name__)

REPORT_FILE = "reports/health-report.json"


@app.route("/")
def dashboard():

    # Run the MQ health check inside the Docker container
    try:
        result = subprocess.run(
            [
                "docker",
                "compose",
                "run",
                "--rm",
                "mq-health-app"
            ],
            capture_output=True,
            text=True
        )

        # Read the health report generated by the health check
        if os.path.exists(REPORT_FILE):
            with open(REPORT_FILE, "r") as f:
                data = json.load(f)
        else:
            data = {
                "queue_manager": "QM1",
                "host": "172.18.0.1",
                "port": 1414,
                "status": "FAILED",
                "queues": [],
                "error": "Health report was not generated."
            }

        # Make sure a failed Docker health check is reflected in the UI
        if result.returncode != 0:
            data["status"] = "FAILED"

            if "error" not in data:
                data["error"] = (
                    result.stdout.strip()
                    or result.stderr.strip()
                    or "MQ health check failed."
                )

        return render_template(
            "dashboard.html",
            report=data
        )

    except Exception as error:

        data = {
            "queue_manager": "QM1",
            "host": "172.18.0.1",
            "port": 1414,
            "status": "FAILED",
            "queues": [],
            "error": str(error)
        }

        return render_template(
            "dashboard.html",
            report=data
        )


if __name__ == "__main__":
    app.run(
        host="0.0.0.0",
        port=5000,
        debug=True
    )
